[package]
name = "rust-client-snmp-sim"
version = "0.3.0"
edition = "2021"

[dependencies]
rust-client-snmp-sim-lib = { path = "./rust-client-snmp-sim-lib" }

[build-dependencies]
service = { path = "../../", package = "snmp-sim" }
openapi-generator = { path = "../../crates/openapi-generator" }
